version: '3'

services:

  pin-manager-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mysql
    ports:
      - 3306:3306

  myapp-main:
    image: pin_manager_app
    restart: on-failure
    depends_on:
      - pin-manager-mysql
    ports:
      - 8080:8080
    